[package]
name = "attached"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
parking_lot = "0.11"

[dev-dependencies]
criterion = "0.3"
once_cell = "1"
static_init = "1"

[[bench]]
name = "bench1"
harness = false