[package]
name = "attached"
version = "0.1.2-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
once_cell = "1"

[dev-dependencies]
static_init = "1"
criterion = "0.4"
dhat = "0.3"

[[bench]]
name = "bench1"
harness = false
