[package]
name = "attached"
version = "0.1.2-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
static_init = "1"

[dev-dependencies]
criterion = "0.3"
once_cell = "1"

[[bench]]
name = "bench1"
harness = false
